# -*- mode: python ; coding: utf-8 -*-
"""
MiMo TTS 语音合成器 Portable
Single-file executable with embedded Streamlit
"""

import sys
import os
from PyInstaller.utils.hooks import collect_all

# Get spec file directory
spec_dir = os.path.dirname(os.path.abspath(SPECPATH))

# 收集 Streamlit 的所有数据文件（HTML模板、JS、CSS、protobuf等）
streamlit_datas, streamlit_binaries, streamlit_hiddenimports = collect_all('streamlit')

# Data files to include
added_files = [
    ("src/mimo_tts_app.py", "."),
    ("src/redist", "redist"),  # WebView2 引导程序
    ("requirements.txt", "."),
] + streamlit_datas

# 隐藏导入 - 添加所有可能需要的模块
hidden_imports = [
    # Streamlit 核心
    "streamlit",
    "streamlit.web.cli",
    "streamlit.runtime.scriptrunner.script_runner",
    "streamlit.runtime.scriptrunner.exec_code",
    "streamlit.runtime.secrets",
    "streamlit.runtime.state",
    "streamlit.runtime.metrics_util",
    "streamlit.runtime.uploaded_file_manager",
    "streamlit.runtime.memory_session_storage",
    "streamlit.runtime.forward_msg_queue",
    "streamlit.runtime.app_session",
    "streamlit.runtime.caching",
    "streamlit.runtime.caching.cache_data_api",
    "streamlit.runtime.caching.cache_resource_api",
    "streamlit.runtime.caching.storage.cache_storage_protocol",
    "streamlit.runtime.caching.storage.in_memory_cache_storage_wrapper",
    "streamlit.runtime.caching.storage.local_disk_cache_storage",
    "streamlit.runtime.connection",
    "streamlit.delta_generator",
    "streamlit.elements",
    "streamlit.elements.lib",
    "streamlit.elements.lib.policies",
    "streamlit.elements.lib.column_types",
    "streamlit.elements.lib.image_utils",
    "streamlit.elements.lib.utils",
    "streamlit.elements.lib.mutable_status_container",
    "streamlit.elements.lib.dialog",
    "streamlit.elements.lib.pandas_styler_utils",
    "streamlit.elements.arrow",
    "streamlit.elements.iframe",
    "streamlit.elements.html",
    "streamlit.elements.markdown",
    "streamlit.elements.text",
    "streamlit.elements.heading",
    "streamlit.elements.code",
    "streamlit.elements.latex",
    "streamlit.elements.write",
    "streamlit.elements.json",
    "streamlit.elements.metric",
    "streamlit.elements.spinner",
    "streamlit.elements.progress",
    "streamlit.elements.balloons",
    "streamlit.elements.snow",
    "streamlit.elements.toast",
    "streamlit.elements.empty",
    "streamlit.elements.exception",
    "streamlit.elements.form",
    "streamlit.elements.button",
    "streamlit.elements.button_group",
    "streamlit.elements.download_button",
    "streamlit.elements.link_button",
    "streamlit.elements.page_link",
    "streamlit.elements.checkbox",
    "streamlit.elements.radio",
    "streamlit.elements.selectbox",
    "streamlit.elements.multiselect",
    "streamlit.elements.select_slider",
    "streamlit.elements.toggle",
    "streamlit.elements.color_picker",
    "streamlit.elements.date_widgets",
    "streamlit.elements.time_widgets",
    "streamlit.elements.number_input",
    "streamlit.elements.text_widgets",
    "streamlit.elements.text_area",
    "streamlit.elements.camera_input",
    "streamlit.elements.file_uploader",
    "streamlit.components.v1",
    "streamlit.components.v1.component_registry",
    "streamlit.components.v1.custom_component",
    "streamlit.components.types",
    "streamlit.config",
    "streamlit.config_option",
    "streamlit.config_util",
    "streamlit.errors",
    "streamlit.file_util",
    "streamlit.folder_black_list",
    "streamlit.git_util",
    "streamlit.logger",
    "streamlit.net_util",
    "streamlit.platform",
    "streamlit.source_util",
    "streamlit.string_util",
    "streamlit.type_util",
    "streamlit.url_util",
    "streamlit.user_info",
    "streamlit.util",
    "streamlit.version",
    "streamlit.watcher",
    "streamlit.watcher.local_sources_watcher",
    "streamlit.watcher.path_watcher",
    "streamlit.watcher.polling_path_watcher",
    "streamlit.watcher.util",
    "streamlit.proto",
    "streamlit.proto.BackMsg_pb2",
    "streamlit.proto.Block_pb2",
    "streamlit.proto.Common_pb2",
    "streamlit.proto.Components_pb2",
    "streamlit.proto.Delta_pb2",
    "streamlit.proto.Element_pb2",
    "streamlit.proto.ForwardMsg_pb2",
    "streamlit.proto.NewSession_pb2",
    "streamlit.proto.PageConfig_pb2",
    "streamlit.proto.PageInfo_pb2",
    "streamlit.proto.PageProfile_pb2",
    "streamlit.proto.PagesChanged_pb2",
    "streamlit.proto.SessionEvent_pb2",
    "streamlit.proto.SessionStatus_pb2",
    "streamlit.proto.WidgetStates_pb2",
    
    # WebView 相关 - 关键修复
    "webview",
    "webview.platforms",
    "webview.platforms.winforms",
    "webview.platforms.edgechromium",
    "webview.platforms.mshtml",
    "webview.util",
    
    # .NET/CLR 相关
    "clr",
    "pythonnet",
    
    # 系统相关
    "tkinter",
    "tkinter.messagebox",
    "tkinter.filedialog",
    "winreg",
    
    # 网络相关
    "urllib",
    "urllib.request",
    "http.client",
    "socket",
    
    # 其他依赖
    "openai",
    "requests",
    "logging.handlers",
    
    # 常用标准库
    "pathlib",
    "json",
    "re",
    "datetime",
    "typing",
    "collections",
    "functools",
    "itertools",
    "math",
    "random",
    "hashlib",
    "base64",
    "io",
    "tempfile",
    "shutil",
    "inspect",
    "textwrap",
    "string",
    "enum",
    "dataclasses",
    "uuid",
    "warnings",
    "contextlib",
    "types",
    "copy",
    "numbers",
    "decimal",
    "fractions",
    "statistics",
    
    # 第三方库
    "pandas",
    "pandas.core.frame",
    "pandas.core.series",
    "numpy",
    "PIL",
    "PIL.Image",
    "altair",
    "pyarrow",
    "tornado",
    "tornado.web",
    "tornado.ioloop",
    "tornado.gen",
    "tornado.httpserver",
    "tornado.netutil",
    "tornado.platform",
    "tornado.concurrent",
    "tornado.escape",
    "tornado.httpclient",
    "tornado.httputil",
    "tornado.log",
    "tornado.process",
    "tornado.routing",
    "tornado.tcpserver",
    "tornado.util",
    "toml",
    "click",
    "blinker",
    "cachetools",
    "git",
    "gitdb",
    "smmap",
    "packaging",
    "packaging.version",
    "packaging.specifiers",
    "protobuf",
    "google.protobuf",
    "google.protobuf.descriptor",
    "google.protobuf.message",
    "google.protobuf.descriptor_pb2",
    "google.protobuf.internal",
    "tzlocal",
    "pytz",
    "validators",
    "watchdog",
    "watchdog.observers",
    "watchdog.events",
    "rich",
    "rich.console",
    "rich.panel",
    "rich.text",
    "rich.markdown",
    "rich.progress",
    "rich.syntax",
    "rich.table",
    "rich.theme",
    "rich.traceback",
    "pygments",
    "pygments.lexers",
    "pygments.formatters",
    "pygments.styles",
    "markdown",
    "markdown.extensions",
    "markdown_it",
    "mdurl",
    "tenacity",
    "charset_normalizer",
    "certifi",
    "idna",
    "urllib3",
    "yaml",
    "tomli",
    "importlib_metadata",
    "zipp",
    "six",
    "wrapt",
    "jinja2",
    "markupsafe",
    "pydeck",
    "pydeck.io",
    "pydeck.bindings",
    "pydeck.data_utils",
    "pydeck.exceptions",
    "pydeck.frontend_semver",
    "pydeck.nbextension",
    "pydeck.settings",
    "pydeck.types",
    "pydeck.widget",
    "pydeck._version",
]

a = Analysis(
    ["src/desktop_app.py"],
    pathex=[spec_dir],
    binaries=[],
    datas=added_files,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

# Single-file executable (onefile mode)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="MiMoTTS语音合成器",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Single file mode - all in one EXE
    onefile=True,
)
